[IMP] open_academy: Added a dashboard view to visualize session calendar, graph, and courses T#53764
Additionally, encountered the error:

    edit_custom() missing 1 required positional
    argument: 'custom_id'

while attempting to move elements around the dashboard;
solved it by adding a controller with route '/web/view/edit_custom'
that returns {'result': True}.